### ISSUE TITLE
Call to undefined method withMeta() after updating Nova to 3.22.0

### ISSUE THREAD

**Issue by stardothosting** [Krato/NovaLinkResource#9]
Just transitioned my install to a new server and I'm seeing this when attempting to access: 

`Call to undefined method EricLagarda\NovaLinkResource\NovaLinkResource::withMeta() `

The specific function in question is in **vendor/ericlagarda/novalinkresource/src/NovaLinkResource.php** on line 42:

```    
     /**
     * Set the name link
     *
     * @param  array  $name
     *
     * @return array
     */
    public function name($name)
    {
        return $this->withMeta(['name' => $name]);
    }
```

**Comment by stardothosting** [comment]
In my NovaServiceProvider.php I am using it like the following example:

```
      (new NovaLinkResource())
                ->name('WHATEVER')
                ->to('/whatever')
                ->icon('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150" width="24"><path fill="var(--primary-turqoise)" d="M105.47,115.63V34.37h10.17v81.26Zm-71.11,0V34.37H44.53v81.26ZM90.23,90.24V34.37H100.4V90.24Zm-25.39,0V34.37H85.16V90.24Zm-15.24,0V34.37H59.77V90.24Z"/></svg>'),
```

**Comment by stardothosting** [comment]
This was previously working in Nova 3.12.0 and after updating Nova to 3.22.0 this error happened

**Comment by stardothosting** [comment]
Confirmed that Nova 3.19.0 broke this package, specifically this update :

> Fixed issue with using unsupported withMeta method on Tools. [#1148](https://github.com/laravel/nova/pull/1148)

After downgrading to **Nova 3.18.0** , the issue no longer happens.

**Comment by Krato** [comment]
I will check. Please be patient.

**Comment by marcemarin** [comment]
Hello, the same issue here, excelent package @Krato, thank you

**Comment by ugduck-brandon** [comment]
Same issue here. When?

**Comment by Krato** [comment]
Sorry. Not working after some core changes after 3.17: See https://github.com/laravel/nova-issues/issues/3142
